#!/usr/bin/env python3
import time
import termios
import sys

def type_text(text, velocity=0.01):
  for char in text:
      print(char, end='', flush=True)
      time.sleep(velocity)
      
def print_blocking_input(text, speed=0.01):
  fd = sys.stdin.fileno()
  old_settings = termios.tcgetattr(fd)
  try:
    new_settings = termios.tcgetattr(fd)
    new_settings[3] = new_settings[3] & ~termios.ECHO
    termios.tcsetattr(fd, termios.TCSADRAIN, new_settings)
    type_text(text, speed)
    termios.tcflush(sys.stdin, termios.TCIFLUSH)
  finally:
    termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)

#COLOR
RESET = "\033[0m"     #RESET COLOR
RED = "\033[0;31m"      #COMANDOS
GREEN = "\033[0;32m"    #ARQUIVOS DE TEXTO SIMPLES
YELLOW = "\033[33m"   #OBJETIVOS
BLUE = "\033[0;34m"     #DITERORIOS
MAGENTA = "\033[0;35m"  #RESTRITO NOME
CYAN = "\033[0;36m"     #RESTRITO PASTAS
WHITE = "\033[0;1;37m"  #BASH HUNTER NEGRITADO
ORANGE = "\033[38;5;208m" #SCRIPTS
  
# MSG_STRUCTURE
guide_structure = f"""
▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌
{WHITE}
=== GUIA RÁPIDO ===
{RESET}
VOCÊ ESTÁ NA ÁREA DE INSTRUÇÕES DO JOGO!

PARA LER AS INSTRUÇÕES DESSA ÁREA, DIGITE:
{RED}cat{RESET} {GREEN}instrução.txt{RESET}



O COMANDO {RED}cat{RESET} EXIBE O CONTEÚDO DE QUALQUER ARQUIVO
DE TEXTO DIRETAMENTE NO TERMINAL.

{GREEN}instrução.txt{RESET} É O NOME DO ARQUIVO DE TEXTO QUE CONTÉM AS
ORIENTAÇÕES DESSA ÁREA.



{WHITE}
=== ATENÇÃO ===
{RESET}
SEMPRE QUE ESTIVER COM DUVIDAS, USE O COMANDO {RED}sos{RESET} 
PARA RECEBER DICAS E ORIENTAÇÕES SOBRE O JOGO.

SE ESTIVER PERDIDO, USE O COMANDO {RED}mapa{RESET} 
PARA VER O MAPA DA REGIÃO INTERNA.

SE VOCÊ COMEÇAR A DIGITAR UM {RED}COMANDO{RESET}, VOCÊ PODE
AUTO COMPLETAR PRESSIONANDO A TECLA {WHITE}TAB{RESET}. SE O
COMANDO EXISTIR E TIVER CERTO, ELE AUTO COMPLETA.

▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌

"""
print("\033[H\033[J\033[38;5;208m\033[0m") #ir para o topo
print_blocking_input(guide_structure)
