#!/usr/bin/env python3
import os
import time
import termios
import sys

now = os.path.os.getcwd().lower()

#FUNCTION
def destiny():
  if now == "/home/jogador/bash_hunter/play":
      return "Escolha o room que você parou!"
  if now == "/home/jogador/bash_hunter/play/room_01":
      return "para_o_mar"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar":
      return "senhor_do_bonfim"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim":
      return "feira_de_santana"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/andorinha":
      return "senhor_do_bonfim"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/jacobina":
      return "senhor_do_bonfim"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/juazeiro":
      return "senhor_do_bonfim"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana":
      return "salvador"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/barreiras":
      return "feira_de_santana"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/vitoria_da_conquista":
      return "feira_de_santana"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador":
      return "terminal_nautico_de_salvador"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/aracaju":
      return "salvador"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/porto_seguro":
      return "salvador"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/terminal_nautico_de_salvador":
      return "Barcos"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/terminal_nautico_de_salvador/Barcos":
      return "caravela"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/terminal_nautico_de_salvador/Barcos/caravela":
      return "escolher"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/terminal_nautico_de_salvador/Barcos/canoa":
      return "Barcos"
  if "None":
    return "Voltar para o ambiente do jogo."
  
def type_text(text, velocity=0.005):
  for char in text:
      print(char, end='', flush=True)
      time.sleep(velocity)
      
def print_blocking_input(text):
  fd = sys.stdin.fileno()
  old_settings = termios.tcgetattr(fd)
  try:
    new_settings = termios.tcgetattr(fd)
    new_settings[3] = new_settings[3] & ~termios.ECHO
    termios.tcsetattr(fd, termios.TCSADRAIN, new_settings)
    type_text(text)
    termios.tcflush(sys.stdin, termios.TCIFLUSH)
  finally:
    termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)

#COLOR
RESET = "\033[0m"     #RESET COLOR
RED = "\033[0;4;31m"      #COMANDOS
GREEN = "\033[0;4;32m"    #ARQUIVOS DE TEXTO SIMPLES
YELLOW = "\033[33m"   #OBJETIVOS
BLUE = "\033[0;4;34m"     #DITERORIOS
MAGENTA = "\033[35m"  #RESTRITO NOME
CYAN = "\033[36m"     #RESTRITO PASTAS
WHITE = "\033[1;37m"  #BASH HUNTER NEGRITADO

#MESSAGENS ROOMS
objective_room_1 = "Entrar em um barco ápto para longas navegações."
    
#MENSSAGENS
use_cd = f"""{WHITE}-> Digite o comando {RED} cd {BLUE} {destiny()} {WHITE} para você entrar na {BLUE} pasta {destiny()}{RESET}\n""" if destiny() != "None" else f"""{WHITE}-> Use o comando {RED} cd {BLUE} nome_da_pasta {WHITE} ou {RED} cd .. {WHITE} para conseguir voltar no ambiente do jogo.{RESET}\n"""

use_cd_dotdot = f"""{WHITE}-> Digite o comando {RED} cd .. {WHITE} para voltar uma pasta para trás.{RESET}\n""" if destiny() != "None" else f"""{WHITE}-> Use o comando {RED} cd {BLUE} nome_da_pasta {WHITE} para voltar para o ambiente do jogo.{RESET}\n"""

use_ls = f"""{WHITE}-> Use o comando {RED} ls {WHITE} para ver os {GREEN} arquivos {WHITE} e {BLUE} pastas {WHITE} que você pode manipular.{RESET}\n"""

use_ls_a = f"""{WHITE}-> Use o comando {RED} ls -a {WHITE} para ver todos os {GREEN} arquivos {WHITE} e {BLUE} pastas {WHITE} ocultas e não ocultas que você pode manipular.{RESET}\n"""
use_ls_l = f"""{WHITE}-> Use o comando {RED} ls -l {WHITE} para ver os detalhes dos {GREEN} arquivos {WHITE} e {BLUE} pastas {WHITE} que você pode manipular.{RESET}\n"""
use_ls_la = f"""{WHITE}-> Use o comando {RED} ls -la {WHITE} para ver todos os detalhes dos {GREEN} arquivos {WHITE} e {BLUE} pastas {WHITE} ocultas e não ocultas que você pode manipular.{RESET}\n"""
use_cat = f"""{WHITE}-> Use o comando {RED} cat {GREEN} nome_do_arquivo.txt {WHITE} para ver o conteúdo do arquivo.{RESET}\n"""
# use_find = f"""{WHITE}-> Use o comando {RED} find {BLUE} diretório {WHITE} -name {BLUE} "padrão" {WHITE} para buscar arquivos ou pastas.{RESET}\n"""

# MSG_STRUCTURE
sos_structure = f""" 
▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌
                       
=== SOS TUTORIAL ===

Você está em:
{BLUE + now + RESET}

Próximo destino:
{BLUE + destiny() + RESET}

Objetivo do room_1:
{YELLOW + objective_room_1 + RESET}

▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌

"""

print_blocking_input(sos_structure)


def print_help_command():
  if now == "/home/jogador/bash_hunter/play":
      return f"""{use_ls + use_cd}"""
  if now == "/home/jogador/bash_hunter/play/room_01":
      return f"""{use_ls + use_cd}"""
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar":
      return f"""{use_ls + use_cd}"""
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim":
      return f"""{use_ls_l + use_cd}"""
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/andorinha":
      return f"""{use_ls + use_cd_dotdot}"""
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/jacobina":
      return f""" {use_ls_l + use_cd_dotdot} """
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/juazeiro":
      return f""" {use_ls + use_cd_dotdot} """
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana":
      return f""" {use_ls + use_cd} """
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/barreiras":
      return "feira_de_santana"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/vitoria_da_conquista":
      return "feira_de_santana"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador":
      return "terminal_nautico_de_salvador"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/aracaju":
      return "salvador"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/porto_seguro":
      return "salvador"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/terminal_nautico_de_salvador":
      return "Barcos"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/terminal_nautico_de_salvador/Barcos":
      return "caravela"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/terminal_nautico_de_salvador/Barcos/caravela":
      return "escolher"
  if now == "/home/jogador/bash_hunter/play/room_01/para_o_mar/senhor_do_bonfim/feira_de_santana/salvador/terminal_nautico_de_salvador/Barcos/canoa":
      return "Barcos"
  if "None":
    return "Voltar para o ambiente do jogo."
  
print(print_help_command())