#!/usr/bin/env python3
import time
import termios
import sys
import os

def type_text(text, velocity=0.01):
  for char in text:
      print(char, end='', flush=True)
      time.sleep(velocity)
      
def print_blocking_input(text, speed=0.01):
  fd = sys.stdin.fileno()
  old_settings = termios.tcgetattr(fd)
  try:
    new_settings = termios.tcgetattr(fd)
    new_settings[3] = new_settings[3] & ~termios.ECHO
    termios.tcsetattr(fd, termios.TCSADRAIN, new_settings)
    type_text(text, speed)
    termios.tcflush(sys.stdin, termios.TCIFLUSH)
  finally:
    termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)

#COLOR
RESET = "\033[0m"     #RESET COLOR
RED = "\033[0;31m"      #COMANDOS
GREEN = "\033[0;32m"    #ARQUIVOS DE TEXTO SIMPLES
YELLOW = "\033[33m"   #OBJETIVOS
BLUE = "\033[0;34m"     #DITERORIOS
MAGENTA = "\033[0;35m"  #RESTRITO NOME
CYAN = "\033[0;36m"     #RESTRITO PASTAS
WHITE = "\033[0;1;37m"  #BASH HUNTER NEGRITADO
ORANGE = "\033[38;5;208m" #SCRIPTS
  
# MSG_STRUCTURE
wlc_structure = f"""{ORANGE} 
▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌
{RESET}
{WHITE}
🪶 SOBRE O JOGO
{RESET}
Bash Hunter é uma jornada dentro do seu próprio
terminal Linux! Você explorará {BLUE}pastas{RESET}, decifrará pistas 
e navegará por mares digitais em busca de {YELLOW}novos destinos{RESET}.

O jogo é composto por fases chamados de {BLUE}ROOM{RESET}. Cada {BLUE}room{RESET},
tem uma chave que te permite abrir a próxima fase {BLUE}room{RESET}.

Dentro do jogo as {BLUE}pastas{RESET} que também são conhecidas 
pelo nome de {BLUE}diretórios{RESET}, são representadas pela cor 
{BLUE}azul{RESET}. Cada {BLUE}pasta{RESET} tem o nome de uma {BLUE}cidade{RESET} ou {BLUE}objeto{RESET}, 
em que você consegue interagir utilizando {RED}comandos{RESET}.

Os arquivos com a coloração {GREEN}verde{RESET} e com o sufixo "{GREEN}.txt{RESET}"
são arquivos de {GREEN}texto simples{RESET} que contém {GREEN}instruções{RESET} e 
{GREEN}menssagens{RESET} para te ajudar a seguir jogando. para 
conseguir ver o conteúdo dessas {GREEN}menssagens{RESET} é utilizado
um {RED}comando específico{RESET}.

Sempre que precisar de ajuda, use o comando {RED}sos{RESET}.
{WHITE}
---------------------------------------------------------
---------------------------------------------------------
{RESET}
{WHITE}
🪶 PONTO DE PARTIDA
{RESET}
Você começa o jogo nas proximidades da cidade de 
{BLUE}Senhor do Bonfim - BA{RESET}, e o seu primeiro {YELLOW}objetivo{RESET} 
é seguir de {BLUE}cidade{RESET} em {BLUE}cidade{RESET} até chegar no 
{YELLOW}Porto da Baía de Todos os Santos{RESET}, em {BLUE}Salvador - BA{RESET}.

{WHITE}
---------------------------------------------------------
---------------------------------------------------------
{RESET}
{WHITE}
🪶 INSTRUÇÕES
{RESET}
💀 O jogo é composto por {BLUE}rooms{RESET} que são {BLUE}salas{RESET}.
🔑 Cada sala tem uma {YELLOW}chave (key){RESET} que permite seguir para a próxima.
📜 Anote todas as {YELLOW}chaves{RESET} que encontrar — elas serão essenciais
para avançar na jornada!

Boa sorte, marujo! Que os ventos estejam a seu favor!"
{ORANGE}
▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌
{RESET}
"""

print_blocking_input(wlc_structure)
os.system("sleep 5")
os.system("for i in $(seq 1 50); do echo "" && sleep 0.05; done")
