#!/usr/bin/env python3
import time
import termios
import sys

def type_text(text, velocity=0.05):
  for char in text:
      print(char, end='', flush=True)
      time.sleep(velocity)
      
def print_blocking_input(text, speed=0.05):
  fd = sys.stdin.fileno()
  old_settings = termios.tcgetattr(fd)
  try:
    new_settings = termios.tcgetattr(fd)
    new_settings[3] = new_settings[3] & ~termios.ECHO
    termios.tcsetattr(fd, termios.TCSADRAIN, new_settings)
    type_text(text, speed)
    termios.tcflush(sys.stdin, termios.TCIFLUSH)
  finally:
    termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)

#COLOR
RESET = "\033[0m"     #RESET COLOR
RED = "\033[0;31m"      #COMANDOS
GREEN = "\033[0;32m"    #ARQUIVOS DE TEXTO SIMPLES
YELLOW = "\033[33m"   #OBJETIVOS
BLUE = "\033[0;34m"     #DITERORIOS
MAGENTA = "\033[0;35m"  #RESTRITO NOME
CYAN = "\033[0;36m"     #RESTRITO PASTAS
WHITE = "\033[0;1;37m"  #BASH HUNTER NEGRITADO
ORANGE = "\033[38;5;208m" #SCRIPTS
  
# MSG_STRUCTURE
wlc_structure = f"""
{ORANGE} 
▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌
{RESET}
{WHITE}
🪶 SOBRE O JOGO
{RESET}
Bash Hunter é uma jornada dentro do seu próprio terminal Linux!
Você explorará {BLUE}pastas{RESET}, decifrará pistas e navegará por mares 
digitais em busca de novos destinos.

Cada *room* representa uma nova etapa da sua aventura.

Você começa o jogo nas proximidades da cidade de Senhor do Bonfim - BA, 
e o seu primeiro objetivo é seguir de cidade em cidade até chegar 
nos portos da Baía de Todos os Santos, em Salvador - BA.


------------------------------------------------------------

{WHITE}
🪶 INSTRUÇÕES
{RESET}
💀 O jogo é composto por 'rooms' (salas).
🔑 Cada sala tem uma chave (key) que permite seguir para a próxima.
📜 Anote todas as chaves que encontrar — elas serão essenciais
para abrir baús e avançar na jornada!

Boa sorte, marujo! Que os ventos estejam a seu favor!"
{ORANGE}
▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌
{RESET}
"""

print_blocking_input(wlc_structure)

print("")