#!/usr/bin/env python3
import os
import time
import termios
import sys

now = os.path.os.getcwd().lower()

#COLOR
R = "\033[0m"         #RESET COLOR
G = "\033[0;32m"      #GREEN
B = "\033[0;34m"      #BLUE
W = "\033[38;5;94m"   #BROWN
RED = "\033[0;31m"        #COMANDOS
YELLOW = "\033[33m"       #OBJETIVOS
MAGENTA = "\033[0;35m"    #RESTRITO NOME
CYAN = "\033[0;36m"       #RESTRITO PASTAS
WHITE = "\033[0;1;37m"    #BASH HUNTER NEGRITADO
ORANGE = "\033[38;5;208m" #SCRIPTS
H = WHITE
XP = [H,H,H,H,H,H,H,H,H,H]
XR = R

#FUNCTION
def destiny():
  return "nome_da_pasta"
def type_text(text, velocity=0.001):
  for char in text:
      print(char, end='', flush=True)
      time.sleep(velocity)
      
def print_blocking_input(text, speed=0.001):
  fd = sys.stdin.fileno()
  old_settings = termios.tcgetattr(fd)
  try:
    new_settings = termios.tcgetattr(fd)
    new_settings[3] = new_settings[3] & ~termios.ECHO
    termios.tcsetattr(fd, termios.TCSADRAIN, new_settings)
    type_text(text, speed)
    termios.tcflush(sys.stdin, termios.TCIFLUSH)
  finally:
    termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)

def my_location():
  if now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos":
    XP = [G,H,H,H,H,H,H,H,H,H]
  elif now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos/oeste":
    XP = [H,G,H,H,H,H,H,H,H,H]
  elif now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos/oeste/noroeste":  
    XP = [H,H,G,H,H,H,H,H,H,H]
  elif now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos/oeste/noroeste/noroeste":
    XP = [H,H,H,G,H,H,H,H,H,H]
  elif now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos/oeste/noroeste/noroeste/norte":
    XP = [H,H,H,H,G,H,H,H,H,H]
  elif now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos/oeste/noroeste/noroeste/norte/norte":
    XP = [H,H,H,H,H,G,H,H,H,H]
  elif now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos/oeste/noroeste/noroeste/norte/norte/oeste":
    XP = [H,H,H,H,H,H,G,H,H,H]
  elif now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos/oeste/noroeste/noroeste/norte/norte/oeste/noroeste":
    XP = [H,H,H,H,H,H,H,G,H,H]
  elif now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos/oeste/noroeste/noroeste/norte/norte/oeste/noroeste/norte":
    XP = [H,H,H,H,H,H,H,H,G,H]
  elif now == "/home/jogador/bash_hunter/play/room_02/baia_de_todos_os_santos/oeste/noroeste/noroeste/norte/norte/oeste/noroeste/norte/leste":
    XP = [H,H,H,H,H,H,H,H,H,G]
  else:
    XP = [H,H,H,H,H,H,H,H,H,H]


mapa_structure = f""" 
{ORANGE}
▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌
{R}
{WHITE}Google Maps X1:{YELLOW} -12.971106, -38.516105 {R} - {WHITE}Terminal Náutico de Salvador.{R}
{WHITE}Google Maps X2:{YELLOW} -12.746173, -38.622346 {R} - {WHITE}Terminal Náutico de Madre de Deus.{R}
                

{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}*********=**********-=****=**********************-=***:=**********=---= -:-****#:-{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}********==*********=*******#*##**--==***********=*===****:*************-=-###*=---{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}*******==*********=-***==--#**====---=********=:-=---:==**-************=*-###*=*=={R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}*******==*********-****-=-:-==-{B}:::-{W}***:=*****=-**#********=-**********==**==*===**{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}**==*#%###*******==****-:::=*={B}::::-{W}******::***=*#%##*******=**********=*****==*=**{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}*==--=====******=-: : ::-::=*{B}::::-={W}********* -**##=*******-**==****-:-:-=*=-=**-=-{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}-**====************=***-=*{B}:::::::={W}***********=-::::-:::***==*==***=*****=-::***-:#{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}=-=====************==--{B}::::::::::-{W}==-**#*****-=*###****==************:**==**==#-**{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}--=:----=*********=--{B}::::::::::::::{W}=*==*##**=*************=------=****#=***===:  -{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}:=*=**************-{B}:::::::::::::::-{W}=*=*===*-=-:=**********-**#*********=*********#{R}
{B}{B}{W}:=-=*************=*={B}::::::::::::::{XP[8]}X{B}- {XP[9]}X2{B} {W}*##{B}::::-{W}=*=******====*-=*******-******####{R}
{B}{B}{B}{B}{B}{B}{W}:-:**********-===-==-{B}:::::::::::: {XP[7]}X{B}   :{W}== {B}:::::::::{W}=**=-**====**=:=***-=*******#**{R}
{B}{B}{B}{B}{W}:-=**********=*-====-{B}:::::::::::--- {XP[6]}X{B}  -  {XP[5]}X{B} ::::::=*-:::{W}*-:--=*=--=-:-=********=-={R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}:-=************=***={B}:::::::::::::{W}-==-:- {B}-::::::::-{W}***-:=*===**=-=*-***=*******=*=-{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}---*************=={B}:::::::::::::::{W}-==**={B}- :::::::::-{W}**-::******=====-#-#%%#***====*{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}=--*************{B}:::::::::::::::::{W}-****{B}-: ::::::::::{W}**=::=*-==-:**===--*#===****=*={R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}**==***********={B}::::::::::::::::::{W}=**{B}-:  --=::::::-{W}==-::*=*=::=#####*=#%%%%##**==*{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}**=-***********-{B}::::::::::::::::::{W}=**-{B}:- :- ::::::::::::{W}***=::::=****=*#%%#***=***{R}
{B}{B}{B}{B}{B}{B}{B}{W}**=-*******=:=={B}:::::::::::::::::::::::::  {XP[4]}X{B} :::::::::::::::{W}--=*#%%%:*:#*##***==*=={R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}***=::-==*={B}::::::::::::::::::::::::::::: :- :::::::::::::-{W}*#=-*####%:#%#:::::-*#**{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}**==:::===-:=-{B}:::::::::::::::::::::::::: :-:::::::::::::::-{W}=-=*=**#**%#**#%####***{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}**:***=-:::=**----{B}::--:::::::::::::::::  :=-::::::::::::::-{W}*#*=####:%%%****==-=%%%{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}***====*==****: -:---{B}::::::::::::::::::::  :::::::::::::::-{W}#%%#=*# ##%*****=-###%#{R}
{B}{B}{B}{B}{B}{B}{B}{W}**==*********-=---------{B}::::-=::::::::::: {XP[3]}X{B} ::::::::::::::{W}=%%%******#%%##**=*%-:: {R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}*==************-***===-{B}:::-{W}=:*%*-{B}::::::::::: :::::::::::-{W}*#####----##%%#**#**#%:- {R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}:**************==*-{B}:::::::{W}===:*=*=={B}::::::::::  ::::::::::{W}==*#*-##%%#%%#%##%#--:-**{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}=**************-**={B}::::::::::{W}-=****-{B}     ::::  ::::::::-{W}#-*#=-##%#######%%%%%#***%{R}
{B}{B}{B}{B}{B}{W}***************=##{B}::::::::::::{W}-##==*=***={B}:::: {XP[2]}X{B}  ::::={W}####%*-#%%##%%#%%%##%%##%%%%{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}***************=**{B}::::::::::-{W}*==**==-=*-{B}::::::::  :::::{W}####*-%#%%####%%%%%%#%%##=:{R}
{B}{B}{B}{B}{B}{B}{B}{B}{W}***************-=-{B}::::::::::::-{W}*****=###-==={B}:::::  ::::{W}*%%#*-#%##########*--**-{B}:::{R}
{B}{W}**************=*=-{B}:::::::::::-{W}*****===*%----{B}::::: {XP[1]}X{B} {XP[0]}X1{B} *{W}=:  ##%%#####*--{B}::::::::::{R}
{B}{B}{B}{B}{B}{B}{B}{B}{W}**************:=-{B}:::-:::::--{W}********=*#-{B}:::::::::::::{W}*###%######%%#=-{B}:::::::::::::{R}
{B}{B}{B}{B}{B}{B}{B}{B}{W}************* ::-:---{B}::::-{W}#*******#***-{B}::::::::::::-{W}*####%#######-{B}::::::::::::::::{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}===*******===*=:-==-::-=-=*==*****==-{B}::::::::::::::{W}*#%#####%%#*-{B}::::::::::::::::::{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}***===**=*===-=-=**=:--=**#*****#*=-{B}:::::::::::::::------{W}====-{B}::::::::::::::::::::{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}******=-=***=--****-**=--=-==-#*==-{B}:::::::::::::::::::::::::::::::::::::::::::::::{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}*****#***====--************#=*---{B}:::::::::::::::::::::::::::::::::::::::::::::::::{R}
{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{W}**********=*=====*=********-={B}:::::::::::::::::::::::::::::::::::::::::::::::::::::{R}
{ORANGE}
▄ ▄▖▄▖▖▖  ▖▖▖▖▖ ▖▄▖▄▖▄▖
▙▘▌▌▚ ▙▌  ▙▌▌▌▛▖▌▐ ▙▖▙▘
▙▘▛▌▄▌▌▌  ▌▌▙▌▌▝▌▐ ▙▖▌▌
{R}
"""

if now.startswith("/home/jogador/bash_hunter/play/room_02"):
    os.system("clear")
    my_location()
    print(mapa_structure)
